# Generated by Django 2.1.4 on 2018-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(default='', max_length=255)),
                ('nom_producto', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=255)),
                ('tipo_producto', models.CharField(choices=[('Celulares', 'Celulares'), ('ComponectesPC', 'ComponectesPC'), ('Monitores', 'Monitores'), ('Accesorios', 'Accesorios')], default='celulares', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tienda', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('fono', models.CharField(max_length=255)),
                ('correo_elect', models.CharField(max_length=255)),
                ('encargado_local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_vendedor', models.CharField(max_length=255)),
            ],
        ),
    ]
